### ISSUE TITLE
Macroscope 1.7.5 automatically quits after crawl

### ISSUE THREAD

**Issue by csaeum** [nazuke/SEOMacroscope#29] opened 2018-12-03 14:03 UTC
## SEO Macroscope issues

Please note that it can be very useful to provide the URL of the website or pages that you were attempting to crawl with SEO Macroscope. This will greatly aid the debugging process.

If you would prefer not to post a website URL here, then please provide it via the project's main email address:

> seo.macroscope@gmail.com

To aid debugging, it may be necessary to scan a sample of pages of any given URL.

### Actual behavior:
With us Macroscope closes as soon as it has crawled everything.

That is unattractive because we can not read the results. At the moment we make sure that we stop shortly before closing and then export this and then continue to crawl.

Unfortunately, the Continue does not work properly, so it starts again from scratch.

### Steps to reproduce the problem:
Install Download and then have something crawled. I'll try a downgrade to the 1.7.4 if it gets better.

### Operating System version:
Windows 10 64 BIt

**Comment by nazuke** [comment] 2018-12-05 03:49
Thank you for reporting this @csaeum, that sounds like a crashing bug.

Do you have the URL that exhibits this behaviour please?

**Comment by csaeum** [comment] 2018-12-05 08:58
I have fed it with a URL list but this is in a protected area because we are planning a relaunch of the page.

**Comment by nazuke** [comment] 2018-12-07 05:40
OK that is understandable @csaeum, and thank you for the extra information, that helps to nail down where things might be going wrong.

However, I have not yet been able to reproduce the fault on this end.

Do you have any more information as to the exact steps to reproduce this fault please?

For example, did you use:

    File -> Load URL List -> Load from Text File

...or:

    File -> Load URL List -> Paste from Clipboard

And in Preferences, is:

    URL List Processing -> Scan sites in URL List

...checked or unchecked?

Are there any other settings that you altered from the defaults for this task?

(I should probably add a simple method to save/load these Preferences settings...)

**Comment by csaeum** [comment] 2018-12-11 14:10
URL List Processing -> Scan sites in URL List was unchecked and the List was came from both

from Clipboard and from a txt file

**Comment by csaeum** [comment] 2018-12-12 07:13
The error still remains.

I had an URL scanned overnight and this morning the program was over

**Comment by csaeum** [comment] 2018-12-12 23:30
Here Data von MS Errorlog:

Application Error
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-12-12T23:14:11.000000000Z" /> 
  <EventRecordID>156671</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Papa-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SEOMacroscopeSeriesOne.exe</Data> 
  <Data>1.7.5.0</Data> 
  <Data>5bf7a422</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>6.1.7601.24291</Data> 
  <Data>5be785b6</Data> 
  <Data>e0434352</Data> 
  <Data>000000000000bded</Data> 
  <Data>10dc</Data> 
  <Data>01d49268bd2cecc4</Data> 
  <Data>C:\Program Files\SEO Macroscope\SEOMacroscopeSeriesOne.exe</Data> 
  <Data>C:\Windows\system32\KERNELBASE.dll</Data> 
  <Data>a21a9765-fe63-11e8-828a-5404a60f9227</Data> 
  </EventData>
  </Event>

.Net Runtime Error:
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-12-12T23:14:10.000000000Z" /> 
  <EventRecordID>156670</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>Papa-PC</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Anwendung: SEOMacroscopeSeriesOne.exe Frameworkversion: v4.0.30319 Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet. Ausnahmeinformationen: System.ArgumentException bei System.Text.RegularExpressions.RegexParser.ScanRegex() bei System.Text.RegularExpressions.RegexParser.Parse(System.String, System.Text.RegularExpressions.RegexOptions) bei System.Text.RegularExpressions.Regex..ctor(System.String, System.Text.RegularExpressions.RegexOptions, System.TimeSpan, Boolean) bei System.Text.RegularExpressions.Regex.IsMatch(System.String, System.String) bei SEOMacroscope.MacroscopeIntenseKeywordAnalysis.AnalyzeKeywordPresence(SEOMacroscope.MacroscopeDocument) bei SEOMacroscope.MacroscopeDocumentCollection.RecalculateStatsIntenseKeywordAnalysis(SEOMacroscope.MacroscopeDocument) bei SEOMacroscope.MacroscopeDocumentCollection.RecalculateDocCollectionFinal() bei SEOMacroscope.MacroscopeJobWorker+<Execute>d__7.MoveNext() bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() bei System.Threading.ThreadPoolWorkQueue.Dispatch()</Data> 
  </EventData>
  </Event>

hope that helps

**Comment by nazuke** [comment] 2018-12-13 02:33
Many thanks for the excellent feedback @csaeum!

I think that that should be enough information for me to investigate this, and try to reproduce the fault.

It looks like it certainly is dying around the most recently added "RecalculateStatsIntenseKeywordAnalysis" functions.

I'll try and be conservative, but I'll carefully scan the domain that you gave me, and see if I can find out which page triggers the fault. Most likely, there is *something* about a particular page that my code doesn't properly account for, hence the unhandled exception.

**Comment by nazuke** [comment] 2018-12-13 02:34
@csaeum I'll also delete the comment that has your domain in it, as soon as things look good.

It looks like GitHub will keep that in the comment history otherwise.

**Comment by nazuke** [comment] 2018-12-13 02:48
OK, that stack trace was perfect. It looks like I failed to check for null `BodyText` when analyzing keywords in the page's body text.

**Comment by nazuke** [comment] 2018-12-13 04:35
@csaeum this was the page (on the given domain) that caused a crash:

> /bankettmoebel-bankettsuhl/bankettmoebel-stuhlwagen-tischwagen/transportwagen-tischwagen-rund.html

The keywords meta tag appears to be malformed. It has a comma that appears to be embedded into what would otherwise be considered a "keyword". It looks like somebody pasted a description into that field, instead of a keywords list.

In this type of situation, my code will be disregarding that type of problem, and register the keywords meta tag as being invalid.

**Comment by csaeum** [comment] 2018-12-20 09:55
Could you ever complete a new version so that I can test it?

I have the problem right now and so I'm stuck right now.

Although the URL's adapted you mean but still it is over here again and again.

How could I help you and me if the problem is solved?

**Comment by nazuke** [comment] 2019-01-28 03:14
Hi @csaeum, this bug should be fixed in the v1.7.6 release now.

Many thanks for the feedback on this project @csaeum; I'm afraid it can take a while, as I don't always have much spare time to work on this.

**Closed by nazuke** 2019-01-28 03:14 UTC
Labels: bug
